### TEST 0
GET http://localhost:3000/api/
Accept: application/json

### USER INFORMATION
GET http://localhost:3000/api/informacion/alan.turing@usm.cl
Accept: application/json

### USER INFORMATION (NO EXISTE)
GET http://localhost:3000/api/informacion/noexistooo
Accept: application/json

### REGISTRAR USUARIO
POST http://localhost:3000/api/registrar
Content-Type: application/json

{
    "nombre": "Testeo",
    "direccion_correo": "testeo.hola@usm.cl",
    "clave": "123",
    "descripcion": "Hola soy un testeo"
}

### MARCAR CORREO FAVORITO (NO EXISTE USUARIO)
POST http://localhost:3000/api/marcarcorreo
Content-Type: application/json

{
  "direccion_correo": "noexistooo",
  "clave": "123",
  "id_correo_fav": 1
}

### MARCAR CORREO FAVORITO (NO EXISTE CORREO)
POST http://localhost:3000/api/marcarcorreo
Content-Type: application/json

{
  "direccion_correo": "alan.turing@usm.cl",
  "clave": "123",
  "id_correo_fav": 9999
}

### MARCAR CORREO FAVORITO (CORREO NO LE PERTENECE)
POST http://localhost:3000/api/marcarcorreo
Content-Type: application/json

{
  "direccion_correo": "alan.turing@usm.cl",
  "clave": "123",
  "id_correo_fav": 1
}

### MARCAR CORREO FAVORITO
POST http://localhost:3000/api/marcarcorreo
Content-Type: application/json

{
  "direccion_correo": "alan.turing@usm.cl",
  "clave": "123",
  "id_correo_fav": 22
}

### DESMARCAR CORREO FAVORITO (NO EXISTE USUARIO)
DELETE http://localhost:3000/api/desmarcarcorreo
Content-Type: application/json

{
  "direccion_correo": "noexistooo",
  "clave": "123",
  "id_correo": 1
}

### DESMARCAR CORREO FAVORITO (NO EXISTE CORREO)
DELETE http://localhost:3000/api/desmarcarcorreo
Content-Type: application/json

{
  "direccion_correo": "alan.turing@usm.cl",
  "clave": "123",
  "id_correo": 9999
}

### DESMARCAR CORREO FAVORITO
DELETE http://localhost:3000/api/desmarcarcorreo
Content-Type: application/json

{
  "direccion_correo": "alan.turing@usm.cl",
  "clave": "123",
  "id_correo": 22
}


